global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'adapter-api'
    static_configs:
      - targets: ['adapter-api:8080']
    metrics_path: /metrics

  - job_name: 'query-api'
    static_configs:
      - targets: ['query-api:8081']
    metrics_path: /metrics
